config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/first', to: 'static_pages#first', via: 'get'
  match '/second', to: 'static_pages#second', via: 'get'
  match '/third', to: 'static_pages#third', via: 'get'
  match '/fourth', to: 'static_pages#fourth', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def first
  end

  def second
  end

  def third
  end

  def fourth
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.haml
.container
  %hr/
  %h4.text-center @Copyright reserved 2016

app/views/layouts/_header.html.haml
%header
  .navbar.navbar-default.navbar-static-top{:role => "navigation"}
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => "#responsive-menu", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Открыть навигацию
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "Home", root_path ,class: "navbar-brand"
      #responsive-menu.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li
            %a{:href => "#"} Пункт 1
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Развернуть меню
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "First", first_path
              %li
                = link_to "Second", second_path
              %li
                = link_to "Third", third_path
              %li.divider
              %li
                = link_to "Four", fourth_path
          %li
            %a{:href => "#"} Пункт 3
          %li
            %a{:href => "#"} Пункт 4
        %ul.navbar-right.navbar-nav.nav
          %li
            %a{:href => "#"} Registration
          -# Выпадающее меню с формой входа
          %li
            %button.btn.btn-link.btn__nav{:type=>"button", "data-placement" => "bottom", "data-toggle" => "popover", :title => "<h3 class='text-center in__but'>Sign in </h3>", "data-content" => "<form action=''><div class='form-group'><input type='text' class='form-control' placeholder='E-mail' value=''></div><div class='form-group'><input type='password' class='form-control' placeholder='Password' value=''></div><button type='submit' class='btn btn-primary btn__lar'><i class='fa fa-sign-in'></i> ВОЙТИ</button></form>"} Sign in

app/views/layouts/_modal.html.haml
#modal-1.modal.fade
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %i.fa.fa-close
        %h4.modal-title.other-color Название окна
      .modal-body
        %p.other-color Это модальное окно и тут нужно написать его текст
      .modal-footer
        %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Выход

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExampleButtons</title>
  <meta charset="UTF-8">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/modal' %>
<%= yield %>
<%= render 'layouts/footer' %>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script>
  $(function() {
    $('[data-toggle=popover]').popover({html:true});﻿
  });
</script>
<script src="preloader.js" type="text/javascript"></script>
</body>
</html>

app/views/static_pages/first.html.haml
.container
  .row
    .col-xs-12.col-sm-12.col-md-6
      %h1 Кнопки пример 1
      %a.button__first.bg__blue
        %span Читать описание
        .icon
          %i.fa.fa-info-circle
          %i.fa.icon-checkmark
      %a.button__first
        %span Смотреть модули
        .icon
          %i.fa.icon-circle-right.fa-arrow-circle-right
          %i.fa.icon-checkmark
    .col-xs-12.col-sm-12.col-md-6.bg-wh
      %h1 Кнопки пример 2
      %a{:href => "#", class: "thb-btn thb-read-more fa"} Читать далее
      %br/
      %hr/
      %a{:href => "#", class: "thb-btn thb-read-more fa thb-read-more_b"} Читать далее

app/views/static_pages/fourth.html.haml
%h1 It's Fourth page
%p Fourth page

app/views/static_pages/help.html.haml
%h1.text-center Hi gays, i will work there next time
.text-center
  = link_to "Bootstrap", root_path, class: "btn btn-lg btn-success"
%br/
/ Каталог товаров
.container
  .row
    .container
      %ul.nav.nav-pills
        %li.active
          %a{:href => "#"}
            Элемент 1
            %span.badge 18
        %li
          %a{:href => "#"}
            Элемент 2
            %span.badge 58
        %li
          %a{:href => "#"}
            Элемент 3
            %span.badge 32
        %li
          %a{:href => "#"}
            Элемент 4
            %span.badge 11
  %hr/
  .row
    .col-xs-12.col-sm-6.col-md-4.col-lg-4
      .thumbnail
        %img.img-responsive{:alt => "pictures", :src => "http://placehold.it/600x340"}/
        .caption
          %h3 Название поста
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque suscipit reprehenderit velit nam repudiandae blanditiis accusantium voluptas. Quasi, omnis, officia.
          %a.btn.btn-success{:href => "#"}
            Подробнее
            %i.fa.fa-arrow-right
    .col-xs-12.col-sm-6.col-md-4.col-lg-4
      .thumbnail
        %img.img-responsive{:alt => "pictures", :src => "http://placehold.it/600x340"}/
        .caption
          %h3 Название поста
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque suscipit reprehenderit velit nam repudiandae blanditiis accusantium voluptas. Quasi, omnis, officia.
          %a.btn.btn-success{:href => "#"}
            Подробнее
            %i.fa.fa-arrow-right
    .col-xs-12.col-sm-6.col-md-4.col-lg-4
      .thumbnail
        %img.img-responsive{:alt => "pictures", :src => "http://placehold.it/600x340"}/
        .caption
          %h3 Название поста
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque suscipit reprehenderit velit nam repudiandae blanditiis accusantium voluptas. Quasi, omnis, officia.
          %a.btn.btn-success{:href => "#"}
            Подробнее
            %i.fa.fa-arrow-right
    .col-xs-12.col-sm-6.col-md-4.col-lg-4
      .thumbnail
        %img.img-responsive{:alt => "pictures", :src => "http://placehold.it/600x340"}/
        .caption
          %h3 Название поста
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque suscipit reprehenderit velit nam repudiandae blanditiis accusantium voluptas. Quasi, omnis, officia.
          %a.btn.btn-success{:href => "#"}
            Подробнее
            %i.fa.fa-arrow-right
    .col-xs-12.col-sm-6.col-md-4.col-lg-4
      .thumbnail
        %img.img-responsive{:alt => "pictures", :src => "http://placehold.it/600x340"}/
        .caption
          %h3 Название поста
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque suscipit reprehenderit velit nam repudiandae blanditiis accusantium voluptas. Quasi, omnis, officia.
          %a.btn.btn-success{:href => "#"}
            Подробнее
            %i.fa.fa-arrow-right
    .col-xs-12.col-sm-6.col-md-4.col-lg-4
      .thumbnail
        %img.img-responsive{:alt => "pictures", :src => "http://placehold.it/600x340"}/
        .caption
          %h3 Название поста
          %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque suscipit reprehenderit velit nam repudiandae blanditiis accusantium voluptas. Quasi, omnis, officia.
          %a.btn.btn-success{:href => "#"}
            Подробнее
            %i.fa.fa-arrow-right
/ Пагинация
%nav.text-center
  %ul.pagination.pagination-lg
    %li.disabled
      %a{:href => "#"}
        %i.fa.fa-chevron-left
        %i.fa.fa-chevron-left
    %li.disabled
      %a{:href => "#"}
        %i.fa.fa-chevron-left
    %li.active
      %a{:href => "#"} 1
    %li
      %a{:href => "#"} 2
    %li
      %a{:href => "#"} 3
    %li
      %a{:href => "#"} 4
    %li
      %a{:href => "#"} 5
    %li
      %a{:href => "#"} 6
    %li
      %a{:href => "#"}
        %i.fa.fa-chevron-right
    %li
      %a{:href => "#"}
        %i.fa.fa-chevron-right
        %i.fa.fa-chevron-right
/ Pager(next previous)
.container
  %nav
    %ul.pager
      %li.previous
        %a{:href => "#"} ← Старые записи
      %li.next.disabled
        %a{:href => "#"} Новые записи →

app/views/static_pages/third.html.haml
%h1 It's Third page
%p Third page